LEDGER_CREDIT = "CREDIT"
LEDGER_HOLD = "HOLD"
LEDGER_DEBIT = "DEBIT"
LEDGER_RELEASE = "RELEASE"

LEDGER_INFLOW_TYPES = (LEDGER_CREDIT, LEDGER_RELEASE)
LEDGER_OUTFLOW_TYPES = (LEDGER_DEBIT, LEDGER_HOLD)

PAYOUT_PENDING = "pending"
PAYOUT_PROCESSING = "processing"
PAYOUT_COMPLETED = "completed"
PAYOUT_FAILED = "failed"

VALID_TRANSITIONS = {
    PAYOUT_PENDING: {PAYOUT_PROCESSING},
    PAYOUT_PROCESSING: {PAYOUT_COMPLETED, PAYOUT_FAILED},
}

MAX_PAYOUT_RETRIES = 3
PAYOUT_STUCK_AFTER_SECONDS = 30
